import { defineConfig } from 'eslint/config';
import tseslint from 'typescript-eslint';

export default defineConfig(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.next/**',
      'supabase/functions/**', // Deno runtime; linted separately
      'coverage/**',
    ],
  },
  tseslint.configs.strictTypeChecked,
  {
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // Money safety: floats never carry financial values (CLAUDE.md Law 4).
      // Bans loss-prone Number<->bigint coercion patterns at lint time.
      'no-loss-of-precision': 'error',
      '@typescript-eslint/no-unsafe-argument': 'error',
      'no-restricted-syntax': [
        'error',
        {
          selector: "CallExpression[callee.name='parseFloat']",
          message:
            'parseFloat is banned in financial code. Use minor-unit bigint parsing from @keel/ledger.',
        },
        {
          selector: "MemberExpression[object.name='Math'][property.name='round']",
          message: 'Math.round on money is banned. Use largest-remainder allocation in @keel/ledger.',
        },
      ],
    },
  },
  {
    files: ['**/*.config.js', '**/*.config.ts', 'scripts/**/*.mjs'],
    extends: [tseslint.configs.disableTypeChecked],
  },
  {
    // Generated by Next.js.
    ignores: ['apps/web/next-env.d.ts'],
  },
  {
    files: ['**/*.test.ts'],
    rules: {
      '@typescript-eslint/no-non-null-assertion': 'off',
    },
  },
  {
    // Integration tests probe untyped wire responses on purpose; the unsafe-
    // any family is noise here. Domain packages keep the strict rules.
    files: ['tests/integration/**/*.ts'],
    rules: {
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',
      '@typescript-eslint/restrict-template-expressions': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
    },
  },
);
