import { defineConfig } from 'eslint/config';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';

export default defineConfig(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.next/**',
      'supabase/functions/**', // Deno runtime; linted separately
      'coverage/**',
      // Agent git worktrees are FULL copies of this repo. Linting them made
      // `eslint .` walk the codebase once per worktree and OOM the V8 heap
      // locally (CI never noticed — no worktrees on a fresh checkout).
      '.claude/**',
      // Throwaway reproduction scratch, deliberately outside every tsconfig —
      // typed linting can only report it as a parsing error.
      '.debug/**',
    ],
  },
  tseslint.configs.strictTypeChecked,
  {
    // Rules of Hooks as a hard gate: a conditional hook crashed the entire
    // dashboard at runtime while typecheck+lint stayed green (Wave 0 P0,
    // caught only by live-UI verification). Never again via static means.
    files: ['apps/web/**/*.{ts,tsx}'],
    plugins: { 'react-hooks': reactHooks },
    rules: {
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
    },
  },
  {
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // Money safety: floats never carry financial values (CLAUDE.md Law 4).
      // Bans loss-prone Number<->bigint coercion patterns at lint time.
      'no-loss-of-precision': 'error',
      '@typescript-eslint/no-unsafe-argument': 'error',
      'no-restricted-syntax': [
        'error',
        {
          selector: "CallExpression[callee.name='parseFloat']",
          message:
            'parseFloat is banned in financial code. Use minor-unit bigint parsing from @keel/ledger.',
        },
        {
          selector: "MemberExpression[object.name='Math'][property.name='round']",
          message: 'Math.round on money is banned. Use largest-remainder allocation in @keel/ledger.',
        },
      ],
    },
  },
  {
    files: [
      '**/*.config.js',
      '**/*.config.ts',
      '**/*.config.mjs',
      'scripts/**/*.mjs',
      // Hand-written ambient types for the .mjs scripts above; deliberately
      // outside every tsconfig, so typed linting can only fail to resolve it.
      'scripts/**/*.d.mts',
    ],
    extends: [tseslint.configs.disableTypeChecked],
  },
  {
    // Generated by Next.js.
    ignores: ['apps/web/next-env.d.ts'],
  },
  {
    files: ['**/*.test.ts'],
    rules: {
      '@typescript-eslint/no-non-null-assertion': 'off',
      // A test double must MATCH an async signature (a fetch stub returns a
      // Promise whether or not it awaits internally), so this fires on correct
      // code and carries no safety value here. Still enforced in src/.
      '@typescript-eslint/require-await': 'off',
    },
  },
  {
    // Export tests intentionally parse unknown JSON wire envelopes and build
    // malformed DTOs to prove fail-closed behavior.
    files: ['packages/exports/test/**/*.ts'],
    rules: {
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unnecessary-type-assertion': 'off',
      '@typescript-eslint/no-confusing-void-expression': 'off',
    },
  },
  {
    // Integration tests probe untyped wire responses on purpose; the unsafe-
    // any family is noise here. Domain packages keep the strict rules.
    files: ['tests/integration/**/*.ts'],
    rules: {
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',
      '@typescript-eslint/restrict-template-expressions': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
    },
  },
);
